### ISSUE TITLE
how to disable notifier when I open a specific controller

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [rwbutler/Connectivity#10]
I set notifier to observe connectivity status and it's observe only when internet disconnected, my problems are:
1- the notifier doesn't work when internet back online
2- I want to disable the global notifier in app delegate when I open a specific controller

thanx

**Comment by rwbutler** [comment]
I'm aware of the issue in 1) - it's a bug with Reachability in the simulator not detecting the network adapter state change I believe. If you run on a physical device you should find that it works correctly.

For 2) I would suggest stopping the notifier before pushing / presenting the view controller however if this isn't possible for whatever reason and your `Connectivity` object is a property of your app delegate then you should be able to invoke it with something along the lines of:

```
if let delegate = UIApplication.shared.delegate as? AppDelegate {
    delegate.connectivity.stopNotifier()
}
```
or
```
let delegate = UIApplication.shared.delegate as? AppDelegate
delegate?.connectivity.stopNotifier()
```
Just replace `AppDelegate` with your app delegate class. Hope this helps.

**Comment by BurierAbdalwahhabElia** [comment]
thanx bro, you save my day.
I am very grateful!
