### ISSUE TITLE
how to let notifier in appDelegate work in all viewController by a label indicate internet status 

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [rwbutler/Connectivity#13]
I want to create label in all viewControllers And I want the labels always indicate a connection status in any viewController I open.
thanx.

**Comment by rwbutler** [comment]
The simplest thing you could do is create a static variable in your app delegate (or preferably another location where you can get hold of the variable) and then access the value wherever you need it:

e.g. create the variable:

```swift
var connectivityStatus: Connectivity.Status?
```

 ensuring you set its value somewhere in the app delegate:

```swift
let connectivity = Connectivity()
connectivity.checkConnectivity { [weak self] connectivity in
    self?.connectivityStatus = connectivity.status
}
```

and then in your view controller:

```swift
if let appDelegate = UIApplication.shared.delegate as? MyAppDelegate,
    let status = appDelegate.connectivityStatus {
    myLabel.text = status.description
}
```

Hope this helps 👍🏻
