### ISSUE TITLE
`successThrehold` is not actually configurable

### ISSUE THREAD

**Issue by genericwoods** [rwbutler/Connectivity#16]
I may be missing something here, but it seems `successThrehold` is supposed to be configurable, but I can’t figure out a way to do so, due to access control issues.

The initializer for ConnectivityPercentage and the value property are both marked as `internal`

![Screen Shot 2019-03-25 at 3 54 11 PM](https://user-images.githubusercontent.com/1838637/54950894-bb32f880-4f18-11e9-810b-7708be92ac98.png)
 
![Screen Shot 2019-03-25 at 3 53 16 PM](https://user-images.githubusercontent.com/1838637/54950900-be2de900-4f18-11e9-8487-ec453a1a4ef3.png)

**Comment by genericwoods** [comment]
Somewhat relatedly – I would love to be able to configure the timeout as well. We’re noticing some false-positives for users on slow connections

**Comment by rwbutler** [comment]
That's a good spot, the initializer for `Connectivity.Percentage` should be `public`. I've updated this in 2.2.1. You should then be able to configure the success threshold with:

```swift
connectivity.successThreshold = Connectivity.Percentage(50.0)
```
as in your second example. It should already be possible to configure the timeouts as follows:

```swift
let config = URLSessionConfiguration()
config.timeoutIntervalForRequest = 10.0
config.timeoutIntervalForResource = 10.0
Connectivity.urlSessionConfiguration = config
```

Hope this helps 👍🏻

**Comment by genericwoods** [comment]
@rwbutler thank you for the prompt fix!

**Comment by rwbutler** [comment]
No problem 🙂👍🏻

**Comment by danielsefton** [comment]
Hi, despite the update above I can't seem to configure the property from Objective-C.
