### ISSUE TITLE
Internet Connection Keep Loss

### ISSUE THREAD

**Issue by billionssg** [rwbutler/Connectivity#17]
Here is the step:
- Set my iPad network to 100% Loss 
- Wait it about 45 minutes. 
- Turn off 100% Loss (Bring back network to normal)

It keep hit https://www.apple.com/library/test/success.html with timeout result (it supposed to be 200 OK). But if I wait about 2 minutes, the network is back to normal. 

Any idea?

**Comment by rwbutler** [comment]
Could you provide a little more information to help diagnose the problem, could I ask:

- Are you experiencing this on the simulator or a physical device?
- How are you simulating packet loss?

Thanks in advance.

**Comment by billionssg** [comment]
1. I am experiencing this on physical device

2. I am simulating my packet loss by using Network Link Conditioner. Here is the screenshot:
![IMG_0016](https://user-images.githubusercontent.com/5228251/57517521-3a518400-7341-11e9-8ea6-df30682d95cb.PNG)

**Comment by rwbutler** [comment]
Thanks for the info - I'll investigate. One more question, are you using the default settings?

**Comment by billionssg** [comment]
yes, I am using default settings. I have tried with 4 iPads and all of them are affected

**Comment by billionssg** [comment]
hi @rwbutler,

is there any update?

**Comment by rwbutler** [comment]
I tried to replicate your experiment this morning using an iPad running the example app that comes with the library and enabling polling. If I use the Network Link Conditioner to simulate 100% packet loss  for half an hour then switch to 3G simulation the example app does detect the availability of Internet access. Could I ask are you using example app for your experiment? If you are using your own implementation, then the first thing I'd suggest is ensuring that the Connectivity object in your app is not being released over the period of time that you are testing. It would also be interesting to see whether if you repeat your experiment using the sample app whether you still experience the issue (if you attempt this you will need to add a line of code to enable polling).

**Comment by rwbutler** [comment]
I was curious to know whether you managed to take a look to see whether the reference to the Connectivity object was being released at any point over the duration of your test? I'm going to close this issue for now but if you make any further progress with this, add a comment and we'll re-open this and investigate further.
