### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by rushilMethsof** [rwbutler/Connectivity#18]
Is it possible to use this library in Objective C project?
If yes some documentation would be great.

**Comment by markltownsend** [comment]
This would be the same as running and Swift code in an objective c project. Look at Apple’s book on the subject: https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewBook?id=888894773

**Comment by rushilMethsof** [comment]
Unfortunately that link does not seem to be available in Australian store
I have tried importing the module

`
#import "GenericUIViewController.h"
#import <Connectivity/Connectivity-swift.h>
#import "ProjectName-Swift.h"

@interface GenericUIViewController ()

@end

@implementation GenericUIViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    Connectivity *con = [Connectivity init];   (* use of undeclared identifier Connectivity)
}
@end`

**Comment by markltownsend** [comment]
Sorry about that. Here are the docs from Apple: https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c

**Comment by rushilMethsof** [comment]
It'd be great if someone can get it working on objective c and give a thumbs up.
So far I am not able to utilize it after trying various approaches.
It looks like it might be missing few classes that needs to be extended or @objc Attribute??? I could be entirely wrong.

**Comment by rwbutler** [comment]
Sorry about the delay with this one, Connectivity was originally meant to be used primarily with Swift but there shouldn't really be a barrier to using it with Objective-C. I released an update making Connectivity an `NSObject` subclass which should make it easier to work with from Obj-C. Try out version 3.0.1, I've put together some  sample code to help you get started:

```swift
#import "ViewController.h"
@import Connectivity;

@interface ViewController ()

@property(nonatomic, strong) Connectivity *connectivity;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    _connectivity = [[Connectivity alloc] initWithShouldUseHTTPS:YES];
    [_connectivity setWhenConnected:^(Connectivity * connectivity) {
        // TODO
    }];
    [_connectivity setWhenDisconnected:^(Connectivity * connectivity) {
        // TODO
    }];
    dispatch_queue_global_t backgroundQueue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0);
    [_connectivity startNotifierWithQueue:backgroundQueue];
}

@end
```

Hope this helps 👍🏻

**Comment by rushilMethsof** [comment]
Thanks a lot,
I ended up creating a swift wrapper to access the connectivity object and it worked fine.
Hopefully sample and update provided would help someone else in future.

**Comment by rwbutler** [comment]
Glad you managed to get it working using the wrapper 👍🏻

**Comment by inPhilly** [comment]
I cannot set framework to Network framework (as opposed to System Configuration) when this is used in Objective-C. Am I missing something?

**Comment by rwbutler** [comment]
Try:

```objc
[_connectivity setFramework:ConnectivityFrameworkNetwork];
```
I've made the `Connectivity.Framework` enum Obj-C compatible from release 3.3.1 onwards. Hope this helps!
