### ISSUE TITLE
Notifier not working well

### ISSUE THREAD

**Issue by maulik6994** [rwbutler/Connectivity#21]
notifier is not working when internet connectivity is gone and arrive it is not changing the stats.

**Comment by rwbutler** [comment]
Could I ask are you observing this in the iOS simulator?

**Comment by rwbutler** [comment]
I believe this is a known simulator issue. If you try this out on a physical device you should find that everything behaves as expected 👍🏻

If not, let me know and provide me with a few more details regarding how you're running this and I'll be happy to look into things further.

**Comment by maulik6994** [comment]
Hello @rwbutler, I have tested on the real iPhone device.

**Comment by rwbutler** [comment]
Could you provide me with a little more information to reproduce the issue? Some steps to reproduce as well as your implementation would be useful if you're willing to share? Thanks in advance.

**Comment by maulik6994** [comment]
I have downloaded your demo. Then run on Device. Connect my other device as a hotspot and turn of and on the mobile data.

**Comment by rwbutler** [comment]
Is the notifier running? You need to have pressed the *start notifier* button in the example app for the status to update in realtime.

**Comment by maulik6994** [comment]
@rwbutler can I check this functionality on tap?

**Comment by rwbutler** [comment]
Assuming you mean in your own application - it sounds like what you need is to perform a one-off check: 

https://github.com/rwbutler/Connectivity#one-off-checks

**Comment by maulik6994** [comment]
@rwbutler  it is not going inside the switch statement.

`let connectivity = Connectivity()

connectivity.checkConnectivity { connectivity in

	switch connectivity.status {
		case .connected: 
			break
		case .connectedViaWiFi:
			break
		case .connectedViaWiFiWithoutInternet:
			break
		case .connectedViaWWAN:
			break
		case .connectedViaWWANWithoutInternet:
			break
		case .notConnected:
			break
	}
}`

**Comment by rwbutler** [comment]
You need to ensure that the Connectivity object is retained somewhere in your code otherwise there is potential for it to be released before the callback is invoked. For example if you were using this in a view controller:

```swift

import UIKit
import Connectivity

class ViewController: UIViewController {

    fileprivate let connectivity: Connectivity = Connectivity()

    override func viewDidLoad() {
        super.viewDidLoad()
        connectivity.checkConnectivity { connectivity in
            switch status {
                ...
            }
        }
    }

}
```

See the example `ViewController` in the example app.

**Comment by maulik6994** [comment]
@rwbutler Now it's working well!...Thanking you.

if You would clarify the **retained** things in the documentation than it is better.

**Comment by maulik6994** [comment]
@rwbutler I want to use this is one of a Boolean function which I have created.

Which only return true or false in Boolean.

**Comment by maulik6994** [comment]
Hey, @rwbutler I am using this library with notifier but I have to do always stop the notifier to get the latest update of internet connectivity.

**Comment by rwbutler** [comment]
If you want to use the notifier then you will need something along the lines of the following:
https://github.com/rwbutler/Connectivity#callbacks

If you only want a `Bool` then you can do something such as:

```swift
func updateConnectionStatus(_ status: Connectivity.ConnectivityStatus) -> Bool {

    switch status {
      case .connected:
	    case .connectedViaWiFi, .connectedViaWWAN:
                return true
	    case .notConnected, .connectedViaWWANWithoutInternet, .connectedViaWiFiWithoutInternet:
                return false
    }
        
}
```

**Comment by maulik6994** [comment]
@rwbutler Notifier is not every time to catch the changes in Internet availability.

**Comment by rwbutler** [comment]
Is this on a physical device or on the simulator?

**Comment by maulik6994** [comment]
Real physical device

**Comment by rwbutler** [comment]
Could you provide me more details around the issue you're experiencing?

**Comment by maulik6994** [comment]
Yes, 

I have run your demo app (just change the bundle id)  on Device. Connected with other device as Hotspot.

Then Start the Notifier 
(Hotspot **has** internet availability) - Working perfectly, After a few minutes I have turned off the mobile data of the second device( Now, Hotspot **hasn't** internet availability ) still,  the demo shows Green UI (means still connected to the internet) Not changed for a long time.

I think that's' the issue.

**Comment by rwbutler** [comment]
Ok thanks - I'll try out your specific case.

**Comment by maulik6994** [comment]
Hey, @rwbutler Are you getting this. Please let me know the solution if you found.

**Comment by rwbutler** [comment]
I thought about this and realised that since the state of your network adapter isn't changing (because your device remains connected to the hotspot throughout your test) you will need to enable polling in order to detect the change in connectivity. You can enable this by setting the `isPollingEnabled` property as follows:

https://github.com/rwbutler/connectivity#polling

If you opt use polling, I *strongly* suggest hosting your own connectivity URL as described here:

https://github.com/rwbutler/connectivity#connectivity-urls

This involves hosting a small HTML page somewhere (see here: https://github.com/rwbutler/connectivity#how-it-works) and passing the URL to the library as above.

Particularly when using polling, when you are done, be sure to call `stopNotifier()` to avoid spamming the connectivity endpoints.
