### ISSUE TITLE
[Question] Usage in combination with NEHotspotConfiguration

### ISSUE THREAD

**Issue by farizadp** [rwbutler/Connectivity#23]
Hi @rwbutler .
Can the ```Connectivity``` be used in combination with ```NEHotspotConfigurationManager```? We are thinking of an iOS app that programatically connects to a wifi hotspot (by using ```NEHotspotConfigurationManager```) that doesn't have internet behind it. And I wonder if ```Connectivity``` can be used next to it to prevent the hotspot's captive page from being shown when connected.

**Comment by rwbutler** [comment]
Connectivity can be used to detect whether a captive portal is being shown or not and based on this you may take appropriate action in your app - it doesn't prevent the page from being shown unfortunately. Hope this answers the question?

**Comment by farizadp** [comment]
> 
> 
> it doesn't prevent the page from being shown unfortunately. Hope this answers the question?

This answers the question, thank you
