### ISSUE TITLE
v3.1.1/cocoapods prevents app to run on iOS 12

### ISSUE THREAD

**Issue by nimau** [rwbutler/Connectivity#25]
Hi,
When I use the latest version (3.1.1) with Cocoapods, the application crash at startup on iOS 12:
dyld: Library not loaded: /System/Library/Frameworks/Network.framework/Network
  Referenced from: /private/var/containers/Bundle/Application/EE5181E3-B675-4D6E-AD0D-6BFF8453272C/MAIF.app/Frameworks/Connectivity.framework/Connectivity
  Reason: image not found

All is working fine if I set the version to 3.1.0 in the pod file:
pod 'Connectivity', '3.1.0'

Thanks in advance,
Nicolas.

**Comment by rwbutler** [comment]
Hi Nicolas,

Thanks for reporting this, could I ask what version of Cocoapods you're using? I created a sample project at https://github.com/rwbutler/ConnectivityTest/ to try to reproduce this but I haven't been able to so far unfortunately. I'd be interested to know whether if you create a new project from scratch in Xcode and integrate Connectivity into it using Cocoapods whether you still experience an issue or whether the issue only occurs in your current project. If so, working out the difference in project settings might be of help in tracking down the issue.

Thanks,

Ross

**Comment by nimau** [comment]
I'm using Cocoapods v1.7.5, Xcode 11.1.

I've just tried with Cocoapods v1.8.0, I've the same issue.

**Comment by rwbutler** [comment]
Thanks for the information, could I ask what your Runpath Search Paths are set to in your build settings?

**Comment by nimau** [comment]
I think it's the use_frameworks! in the pod file.
Adding it in your ConnectivityTest project shows the same error.

**Comment by nimau** [comment]
Dou you have any news why "use_frameworks!" prevents app tu run on iOS 12 with version 3.1.1 but not with version 3.1.0 ?

**Comment by rwbutler** [comment]
As far as I can tell currently (I think) this appears to be a bug with Cocoapods therefore I've raised an issue: [https://github.com/CocoaPods/CocoaPods/issues/9197](https://github.com/CocoaPods/CocoaPods/issues/9197)

**Comment by rwbutler** [comment]
I've replicated this quite a few times on iOS 11 but haven't yet seen this occur on iOS 12. Could you confirm that you are in fact seeing this occur on iOS 12?

**Comment by rwbutler** [comment]
I've attempted a fix in 3.1.2 for the issue with iOS 11.

**Comment by nimau** [comment]
Hi,
Sorry for the delay.
Yes, it was on iOS 11, I don't understand why I thought it was on iOS 12, but you're right the problem was on iOS 11.
I tried with your latest release 3.1.2 and it's now work on iOS 11.
Thanks a lot.

**Comment by rwbutler** [comment]
No problem thanks for getting back me - glad things are working ok for you now 👍🏻
