### ISSUE TITLE
Using Network framework in an Objective-C project

### ISSUE THREAD

**Issue by inPhilly** [rwbutler/Connectivity#29]
I cannot set framework to Network framework (as opposed to System Configuration) when this is used in Objective-C with Carthage. Is there anything I can do to be able to set the framework to Network?

**Comment by inPhilly** [comment]
Additionally, kNetworkConnectivityChangedNotification is not recognized in Objective-C. Sorry to bug you, just having a really hard time with this and desperately need it to work.

**Comment by rwbutler** [comment]
Try:

[_connectivity setFramework:ConnectivityFrameworkNetwork];
I've made the Connectivity.Framework enum Obj-C compatible from release 3.3.1 onwards. Hope this helps!

**Comment by rwbutler** [comment]
In Obj-C all you need is to observe the `NSNotification` named `kNetworkConnectivityChangedNotification` as follows:

```objc
[[NSNotificationCenter defaultCenter] addObserver:self
        selector:@selector(receiveTestNotification:) 
        name:@"kNetworkConnectivityChangedNotification"
        object:nil];
```

**Comment by inPhilly** [comment]
Thank you SO MUCH. You are a literal answer to prayer today.

**Comment by inPhilly** [comment]
Can I ask one more question? If polling is not enabled, how often will Connectivity check connectivity and send notification if it has changed? And does it always check when an app becomes active?

**Comment by inPhilly** [comment]
The reason I am asking is that, when the app returns to active from the background, and the connection has been lost while the app is in the background, it does not immediately notify when the app becomes active again. It takes several seconds to notify. I can perform a check as soon as the app becomes active, but then the notification will also kick in, which could cause duplicate actions if I don't properly deal with it.

**Comment by rwbutler** [comment]
It checks every time `Reachability` or `NWPathMonitor` (depending on the value you use for the `framework` property) detects a change in network adapter state. You can use polling if you need to be made of aware of changes outside of these state changes but in that case I would make sure that you stop polling when you are done checking by calling `stopNotifier()` to avoid spamming the connectivity endpoints. I also recommend setting up your own endpoint e.g. by hosting a small HTML page in an S3 bucket. Hope that helps.

**Comment by inPhilly** [comment]
I am still a little bit confused about `pollingEnabled`. It seems that the default for most apps would be *not* to have it enabled? It probably affects app performance, and it requires the setup of a special URL, right? (by the way I think I have been using it in my live app, which I am about to update, without that URL because I didn't understand to set it up - has that done any damage that you can think of?). How accurate would the `whenConnected/whenDisconnected` notifications be without polling enabled? i.e. how close to the change happening do you think Connectivity would pick it up and `whenConnected/whenDisconnected` called?
