### ISSUE TITLE
Polling is not working on iOS < 10.0

### ISSUE THREAD

**Issue by kodelit** [rwbutler/Connectivity#3]
Hello,
one thing in following code bothers me

https://github.com/rwbutler/Connectivity/blob/91d49891c075b2bf4676c7e9c2e92b0e781135de/Connectivity/Classes/Connectivity.swift#L414-L422

Library deployment target is iOS 8+ but polling seems to be working from iOS 10.
Is there a reason why the library cannot use timer with selector instead of block which is available only from iOS 10?
This feature could be available also on older iOS versions than 10.

Or if not supporting polling for iOS version less than 10 is intentional (but why?) maybe `isPollingEnabled` property should be at least marked with `@available(iOS 10.0, *)` ?

**Comment by rwbutler** [comment]
Originally this was documented as a marginally-used iOS 10 only feature but you're absolutely right there's no reason why one of pre-iOS 10 `scheduledTimer` methods could not have been used - originally it was selected for the nicer block syntax. I've updated this for 2.0.2.
