### ISSUE TITLE
connectivity.status in Objective-C

### ISSUE THREAD

**Issue by inPhilly** [rwbutler/Connectivity#30]
It seems that the connectivity.status property isn't directly available in the Objective-C (Carthage) version of the framework.

**Comment by rwbutler** [comment]
Thanks for letting me know I've fixed this in 3.3.2 👍🏻

**Comment by inPhilly** [comment]
Thank you!

**Comment by inPhilly** [comment]
Until I can implement this, is it about just as accurate to use a 'connected' property set by the `whenConnected/whenDisconnected` completions as to use `connectivity.status`?
