### ISSUE TITLE
Call back work only one time 

### ISSUE THREAD

**Issue by BhaveshKumbhani** [rwbutler/Connectivity#34]
It works only one time, when network status is changed. even set connectivity.pollingInterval but did not get call back. 

Not working at all, every time getting false.

let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
            switch connectivity.status {
            case .connected:
                self?.isReachable = true
                break
            case .connectedViaWiFi:
                self?.isReachable = true
                break
            case .connectedViaWiFiWithoutInternet:
                self?.isReachable = false
                break
            case .notConnected:
                self?.isReachable = false
                break
            case .connectedViaCellular:
                self?.isReachable = true
                break
            case .connectedViaCellularWithoutInternet:
                self?.isReachable = false
                break
            case .determining:
                self?.isReachable = false
                break
            }
            print("connectivityChanged:",connectivity.isConnected)
        }
        
        connectivity.isPollingEnabled = true
        connectivity.pollingInterval = 5
        connectivity.whenConnected = connectivityChanged
        connectivity.whenDisconnected = connectivityChanged
        connectivity.startNotifier()

**Comment by BhaveshKumbhani** [comment]
Not working at al, every time getting false.

**Comment by rwbutler** [comment]
Could you let me know which simulators / devices you have tried and what the steps you took were?

**Comment by BhaveshKumbhani** [comment]
I have test in iOS 12.9" iPad 3rd Gen simulator.

**Comment by rwbutler** [comment]
Thanks for getting back to me - this is known issue with the simulator. You should find that this works correctly on device. It should also work on simulator when `isPollingEnabled = true` and with a suitable polling interval. I have re-tested this morning to confirm that this is the case.

**Comment by BhaveshKumbhani** [comment]
I have tested in Device iPad 3rd Gen. callback works in real device when reachability is changed but status is always getting false, no any luck to get real status.

**Comment by rwbutler** [comment]
When you say the status is always `false` are you referring to `isReachable` or `isConnected`? Could you let me know which case in the enum is being matched when you switch on `connectivity.status`? 

Do you have a strong reference to the connectivity object somewhere in your class? If possible, if you could send more of your class so I could see how things are being used that would be very helpful.
