### ISSUE TITLE
Connectivity return .notconnected even 4G is turned on

### ISSUE THREAD

**Issue by nguyenhuutinh** [rwbutler/Connectivity#35]
![1241577422315_ pic_hd](https://user-images.githubusercontent.com/4114159/71502396-f51b9b80-28aa-11ea-8e73-6d85e41599c9.jpg)
I'm using Connectivity 3.0 for iOS

but some iOS device , detecting is not correct. they actually connecting to internet via 4G but app still show case .notConnected:

do you know why?

**Comment by rwbutler** [comment]
Do you find that this happens on a specific version of iOS? Do the devices definitely have Internet connectivity? Are you able to open a web page such as Microsoft.com in a web browser when the issue occurs?
