### ISSUE TITLE
Does not work in Simulator

### ISSUE THREAD

**Issue by lawgimenez** [rwbutler/Connectivity#36]
**Have tested on a physical device? **
[ ] Yes, I have tested on physical iOS device and the reported issue is still present.

**Does code retain the `Connectivity` object? **
[ ] Yes, my implementation has a strong reference to the `Connectivity` object so that it is not deallocated during use.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rwbutler** [comment]
Please ensure that you have read the documentation before raising a bug report: https://github.com/rwbutler/Connectivity#known-issues
