### ISSUE TITLE
Always returning "connectedViaWiFiWithoutInternet".

### ISSUE THREAD

**Issue by asar1** [rwbutler/Connectivity#37]
I've tested on a physical device.
with a working internet connection it always return this(connectedViaWiFiWithoutInternet) case.
same situation in mobile data case.

**Comment by rwbutler** [comment]
Please could you provide the code you're using to configure the framework so that I may investigate? Thanks.

**Comment by asar1** [comment]
`     func checkReachability(){
        let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
             self?.updateConnectionStatus(connectivity.status)
        }

        connectivity.whenConnected = connectivityChanged
        connectivity.whenDisconnected = connectivityChanged

        connectivity.connectivityURLs = [URL(string: "https://www.apple.com/library/test/success.html")!, URL(string: "https://www.google.com/")!]
        
        connectivity.startNotifier()
         
       if Connectivity.isConnectedToInternet {
             isReachable = true
         }else {
             isReachable = false
         }
}
`

`    func updateConnectionStatus(_ status: ConnectivityStatus) {

        switch status {
        case .connected:
            break
        case .connectedViaWiFi:
            print("Connected to Wifi")
            connectToOpentokSession()
            break
        case .connectedViaWiFiWithoutInternet:
            print("Connected to Wifi but no internet")
            connectToOpentokSession()
            break
        case .notConnected:
            print("Disconnected from internet")
            break
        case .connectedViaCellular:
            print("Connected to Data")
            connectToOpentokSession()
            break
        case .connectedViaCellularWithoutInternet:
            print("Connected to Data but no internet")
            connectToOpentokSession()
            break
        case .determining:
            print("Checking")
            break
        }
    }
`

**Comment by asar1** [comment]
``
func checkReachability(){
        let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
             self?.updateConnectionStatus(connectivity.status)
        }
        connectivity.whenConnected = connectivityChanged
        connectivity.whenDisconnected = connectivityChanged

        connectivity.connectivityURLs = [URL(string: "https://www.apple.com/library/test/success.html")!, URL(string: "https://www.google.com/")!]
        
        connectivity.startNotifier()
         
       if Connectivity.isConnectedToInternet {
             isReachable = true
         }else {
             isReachable = false
         }
}
`

`
func updateConnectionStatus(_ status: ConnectivityStatus) {
        switch status {
        case .connected:
            break
        case .connectedViaWiFi:
            print("Connected to Wifi")
            connectToOpentokSession()
            break
        case .connectedViaWiFiWithoutInternet:
            print("Connected to Wifi but no internet")
            connectToOpentokSession()
            break
        case .notConnected:
            print("Disconnected from internet")
            break
        case .connectedViaCellular:
            print("Connected to Data")
            connectToOpentokSession()
            break
        case .connectedViaCellularWithoutInternet:
            print("Connected to Data but no internet")
            connectToOpentokSession()
            break
        case .determining:
            print("Checking")
            break
        }
    }
``

**Comment by asar1** [comment]
`
func checkReachability(){
        let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
             self?.updateConnectionStatus(connectivity.status)
        }
        connectivity.whenConnected = connectivityChanged
        connectivity.whenDisconnected = connectivityChanged
        connectivity.connectivityURLs = [URL(string: "https://www.apple.com/library/test/success.html")!, URL(string: "https://www.google.com/")!]
        connectivity.startNotifier()
       if Connectivity.isConnectedToInternet {
             isReachable = true
         }else {
             isReachable = false
         }
}

func updateConnectionStatus(_ status: ConnectivityStatus) {
        switch status {
        case .connected:
            break
        case .connectedViaWiFi:
            print("Connected to Wifi")
            connectToOpentokSession()
            break
        case .connectedViaWiFiWithoutInternet:
            print("Connected to Wifi but no internet")
            connectToOpentokSession()
            break
        case .notConnected:
            print("Disconnected from internet")
            break
        case .connectedViaCellular:
            print("Connected to Data")
            connectToOpentokSession()
            break
        case .connectedViaCellularWithoutInternet:
            print("Connected to Data but no internet")
            connectToOpentokSession()
            break
        case .determining:
            print("Checking")
            break
        }
    }
`

**Comment by asar1** [comment]
`func checkReachability(){
    let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
        self?.updateConnectionStatus(connectivity.status)
    }
    connectivity.whenConnected = connectivityChanged
    connectivity.whenDisconnected = connectivityChanged
    connectivity.connectivityURLs = [URL(string: "https://www.apple.com/library/test/success.html")!, URL(string: "https://www.google.com/")!]
    connectivity.startNotifier()
    if Connectivity.isConnectedToInternet {
        isReachable = true
    }else {
        isReachable = false
    }
}

func updateConnectionStatus(_ status: ConnectivityStatus) {
    switch status {
    case .connected:
        break
    case .connectedViaWiFi:
        print("Connected to Wifi")
        connectToOpentokSession()
        break
    case .connectedViaWiFiWithoutInternet:
        print("Connected to Wifi but no internet")
        connectToOpentokSession()
        break
    case .notConnected:
        print("Disconnected from internet")
        break
    case .connectedViaCellular:
        print("Connected to Data")
        connectToOpentokSession()
        break
    case .connectedViaCellularWithoutInternet:
        print("Connected to Data but no internet")
        connectToOpentokSession()
        break
    case .determining:
        print("Checking")
        break
    }
}
`

**Comment by asar1** [comment]
`func checkReachability(){
    let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
        self?.updateConnectionStatus(connectivity.status)
    }
    connectivity.whenConnected = connectivityChanged
    connectivity.whenDisconnected = connectivityChanged
    connectivity.connectivityURLs = [URL(string: "https://www.apple.com/library/test/success.html")!, URL(string: "https://www.google.com/")!]
    connectivity.startNotifier()
    if Connectivity.isConnectedToInternet {
        isReachable = true
    }else {
        isReachable = false
    }
}`

`func updateConnectionStatus(_ status: ConnectivityStatus) {
    switch status {
    case .connected:
        break
    case .connectedViaWiFi:
        print("Connected to Wifi")
        connectToOpentokSession()
        break
    case .connectedViaWiFiWithoutInternet:
        print("Connected to Wifi but no internet")
        connectToOpentokSession()
        break
    case .notConnected:
        print("Disconnected from internet")
        break
    case .connectedViaCellular:
        print("Connected to Data")
        connectToOpentokSession()
        break
    case .connectedViaCellularWithoutInternet:
        print("Connected to Data but no internet")
        connectToOpentokSession()
        break
    case .determining:
        print("Checking")
        break
    }
}`

**Comment by asar1** [comment]
```
        let connectivityChanged: (Connectivity) -> Void = { [weak self] connectivity in
             self?.updateConnectionStatus(connectivity.status)
        }

        connectivity.whenConnected = connectivityChanged
        connectivity.whenDisconnected = connectivityChanged

        connectivity.connectivityURLs = [URL(string: "https://www.apple.com/library/test/success.html")!, URL(string: "https://www.google.com/")!]
        
        connectivity.startNotifier()

```
        switch status {
        case .connected:
            break
        case .connectedViaWiFi:
            print("Connected to Wifi")
            connectToOpentokSession()
            break
        case .connectedViaWiFiWithoutInternet:
            print("Connected to Wifi but no internet")
            connectToOpentokSession()
            break
        case .notConnected:
            print("Disconnected from internet")
            break
        case .connectedViaCellular:
            print("Connected to Data")
            connectToOpentokSession()
            break
        case .connectedViaCellularWithoutInternet:
            print("Connected to Data but no internet")
            connectToOpentokSession()
            break
        case .determining:
            print("Checking")
            break
        }
    }

**Comment by rwbutler** [comment]
Thanks for posting your code - from your sample I can see that the issue is the connectivity URLs you are using. You can't use a URL such as `https://www.google.com/` as this URL does not host a HTML page as `https://www.apple.com/library/test/success.html` does. The content of the page should look roughly as follows:

```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<HTML>
<HEAD>
	<TITLE>Success</TITLE>
</HEAD>
<BODY>
	Success
</BODY>
</HTML>
```

I would suggest instead hosting your own HTML file (as above) somewhere and then using the URL to that page if possible.
