### ISSUE TITLE
Switch from Reachability to ReachabilitySwift

### ISSUE THREAD

**Issue by Panajev** [rwbutler/Connectivity#39]
**Is your feature request related to a problem? Please describe.**
Reachability class used is based on the old Objective-C sample, while there are updated and modern Swift re-implementations.

We used to use Reachability directly, then https://github.com/tonymillion/Reachability, and then https://github.com/ashleymills/Reachability.swift ... We are considering Connectivity now as it handles captive portals and network gateways connectivity drops better. While with iOS12+ the new Network framework by Apple replaces the previous SystemConfiguration one, it would be good to have a more modern migration path for it.

**Describe the solution you'd like**
Switch from Apple's Reachability to Ashley Mills's popular ReachabilitySwift implementation which is a quite isolated and well designed replacement: https://github.com/ashleymills/Reachability.swift

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by rwbutler** [comment]
Thanks for raising this issue - making Connectivity a fully-Swift project has been an ambition of mine for some time so this is something I'll look into (it only hasn't happened so far due to a lack of time). In the meantime, functionally it shouldn't make any difference to the way Connectivity behaves using Apple's Obj-C Reachability vs Reachability.swift unless there's a more specific concern.

**Comment by Panajev** [comment]
Hello @rwbutler 

Thanks for the response, I did not expect it this quickly hehe :), very appreciated!
I was hoping it would come after the PR opened... oh well :D.

I opened a PR to integrate ReachabilitySwift (see link above). I noticed that both in my fork with the changes as well as master without any change, one of the tests fails if you do not modify it. What do you think?

**Comment by rwbutler** [comment]
Thanks for taking the time to raise the PR, I very much appreciate it - I'd rather replace the Reachability component without bringing in a third party dependency ideally so I've closed that PR  (apologies) - I've commented more extensively over there. I agree with the principle of this issue but I'd rather replace just the needed functionality from Apple's Reachability with a Swift component which uses SystemConfiguration framework directly without bringing in another third party dependency ideally.

**Comment by Panajev** [comment]
Thank you for the reply, I fully understand your reasoning.

**Comment by rwbutler** [comment]
If your app supports iOS 13+ or will do when iOS 14 is released shortly then this might be what you were looking for - I've created an offshoot project from Connectivity called Hyperconnectivity which drops Reachability and Objective-C support relying solely on NWPathMonitor and Combine:

https://github.com/rwbutler/Hyperconnectivity
