### ISSUE TITLE
Ensure the Connectivity framework handles its dependency to UIKit implicitly / can work without UIKit too

### ISSUE THREAD

**Issue by Panajev** [rwbutler/Connectivity#43]
Hello @rwbutler  :)

We recently updated to Connectivity 4.1.0 and we noticed some compilation issues with some classes and we noticed it was because UIApplication was not defined in those places. Maybe this added dependency to UIApplication (for the new check on app did become active I would think) can be hidden behind a #if canImport(UIKit) directive?

**Is your feature request related to a problem? Please describe.**
The framework should check if UIKit.UIApplication or just UIKit can be imported (is available) as a condition to declare the new method that depend on UIApplication callbacks like it has been added for v4.1.0. Client applications on macOS or even iOS that were using Connectivity without also importing UIKit (maybe just Foundation) would stop to compile if updated to Connectivity 4.1.0.

**Describe the solution you'd like**
Use #if canImport(UIKit) to wrap the declaration on all UIKit.UIApplication code that depends on it.

Kind Regards,

Goffredo

**Comment by rwbutler** [comment]
Thanks for letting me know about this - I'll try to get it fixed asap. Could you let me know how you're compiling the library presently - is it manual or via Cocoapods, Carthage, SPM? Also what platform are you deploying to? Once I can replicate should be able to get this fixed quickly.

**Comment by Panajev** [comment]
Hey :), No worries things happen. 

Connectivity is embedded via SwiftPM for an iOS project, even if I add manual imports in our code it still complains when it tries to compile Connectivity.swift

**Comment by Panajev** [comment]
`SourcePackages/checkouts/Connectivity/Connectivity/Classes/Connectivity.swift:510:19: use of unresolved identifier 'UIApplication'
[12:33:35]: ▸             name: UIApplication.didBecomeActiveNotification,
[12:33:35]: ▸                   ^~~~~~~~~~~~~`

**Comment by Panajev** [comment]
Hello @rwbutler is there an update on this you could provide? Were you able to reproduce it?

**Comment by rwbutler** [comment]
Apologies for the delay with this one - the day job has been a little busier than normal of late. I was able to reproduce this so should have a fix for you shortly.

**Comment by Panajev** [comment]
Hey @rwbutler I was looking at the open PR's and, with some changes for SwiftPM as the PR seems to
Focus on CocoaPods integration and unfortunately with conflicts that need to be solved too, would the PR that is trying to add macOS support ( https://github.com/rwbutler/Connectivity/pull/42/files ) be a good ground to work the fix into? Would it be preferable to do that after your fix or at the same time?

**Comment by rwbutler** [comment]
Hi @Panajev thanks for the comments - it's probably easiest for me to fix this individually for now without worrying about the additional complexity in any other PRs so for now I've created a fix on the branch `hotfixes/issue-43`. Would you like to try it out to see whether it works for you before I create a release? I've tried it out on my end and it seems to do the trick. Sorry about the delay with this one.

**Comment by Panajev** [comment]
No worries, no apologies needed as this framework is one of the hundreds of thing you have to do and it is not a trivial one either.

I will integrate this branch and let you know the results, thanks :).

**Comment by rwbutler** [comment]
That's great thank you - much appreciated 🙏

**Comment by Panajev** [comment]
I see it is now on master, sorry for not getting around testing it yet, will do it on that branch then

**Comment by rwbutler** [comment]
No problem, I had a bit of time available last night so I was able to merge a few things in - I'd planned to message you to let you know to test by pulling the branch master now rather than the previous branch or a tag. If it looks good, I'll tag a release shortly.

**Comment by Panajev** [comment]
Issue fixed, closing it. Thanks! (tested it with the top of the master branch as of last night)

**Comment by rwbutler** [comment]
Glad it works for you! 🙂
