### ISSUE TITLE
 iOS 8.3 warning when using Connectivity with the SPM in Xcode 12.

### ISSUE THREAD

**Issue by fousa** [rwbutler/Connectivity#46]
When integrating Connectivity with the Swift Package Manager in Xcode 12 (beta 4) than I get the following warning:

`The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.3, but the range of supported deployment target versions is 9.0 to 14.0.99.`

Apparently Xcode 12 dropped support for iOS 8 and this is the issue. I'm not sure if dropping iOS 8.3 support for Connectivity is an option, but I wanted to flag this issue.

**Comment by rwbutler** [comment]
Thanks for letting me know about this - I'll almost certainly end up dropping support for iOS 8 once Xcode 12 GM is released. Until then I'll keep the issue open 👍

**Comment by fousa** [comment]
I'll prepare a pull request and I can merge it whenever you want.

**Comment by rwbutler** [comment]
Appreciate it - thanks! 🙏
