### ISSUE TITLE
Polling interval is not configurable as mentioned in README

### ISSUE THREAD

**Issue by kodelit** [rwbutler/Connectivity#5]
Hello, 
one small thing.

https://github.com/rwbutler/Connectivity/blob/1a121aa27e67ec9e44c4dfdc4c0409ee5146924d/Connectivity/Classes/Connectivity.swift#L83

As you see `pollingInterval` is private, and you mention in description that it is configurable.
To have full access to pooling functionality it would be nice to be able to modify that value.

**Comment by rwbutler** [comment]
That's a good spot - consider it done 👍🏻(in v2.0.3)
