### ISSUE TITLE
Carthage build fails because of "no shared framework schemes"

### ISSUE THREAD

**Issue by muiscatron** [rwbutler/Connectivity#53]
**Have read the known issues? **
[X] Yes, I have read and am familiar with the list of [known issues](https://github.com/rwbutler/Connectivity#known-issues).

**Have tested on a physical device? **
[N/A - can't build ] Yes, I have tested on physical iOS device and the reported issue is still present.

**Does code retain the `Connectivity` object? **
[ N/A - can't build] Yes, my implementation has a strong reference to the `Connectivity` object so that it is not deallocated during use.

**Describe the bug**
Carthage fails to build the code. Error:
*** Skipped building Connectivity due to the error:
Dependency "Connectivity" has no shared framework schemes for any of the platforms: iOS

**To Reproduce**
Create a new Xcode project (Xcode 11.4.1)
Add Cartfile entry:
github "rwbutler/Connectivity"
Run command: carthage update --platform iOS
Error result as above.
Carthage version is 0.3.4

I have tried referencing Connectivity v4 with same result

**Expected behavior**
Carthage should build the framework.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Catalina
 - Browser N/A
 - Version N/A

**Smartphone (please complete the following information):**
N/A 

**Additional context**
N/A

**Comment by kumarGautamAramark** [comment]
I am also getting similar issue on xcode 12 while running `carthage update --platform ios`
I am using Connectivity version 1.3.2.
``
Skipped building Connectivity due to the error:
Dependency "Connectivity" has no shared framework schemes for any of the platforms: iOS
``

**Comment by kumarGautamAramark** [comment]
I am also getting similar issue on xcode 12 while running `carthage update --platform ios`
I am using Connectivity version 1.3.2.
``
Skipped building Connectivity due to the error:
Dependency "Connectivity" has no shared framework schemes for any of the platforms: iOS
``I am also getting similar issue on xcode 12 while running `carthage update --platform ios`
I am using Connectivity version 1.3.2.
``
Skipped building Connectivity due to the error:
Dependency "Connectivity" has no shared framework schemes for any of the platforms: iOS
``

**Comment by muiscatron** [comment]
@kumarGautamAramark Do you have any idea for a workaround?

**Comment by rwbutler** [comment]
Thanks for raising this issue @muiscatron - could try `carthage update` and see whether 5.0.1 works for you?

**Comment by inPhilly** [comment]
I think your 5.0.1 fix may have broken something. I just updated using Carthage and now get this error:
/Users/home/Documents/MyApp/MyApp.xcodeproj Building for iOS Simulator, but the linked framework 'Connectivity.framework' was built for iOS.

**Comment by rwbutler** [comment]
@inPhilly It sounds like when the framework was built it was compiled for iOS (physical device) but not for simulator for some reason. Could you provide me with a little more information regarding:

- The version of Xcode you're using (if you have multiple versions you can find out which one is being used by typing `Xcode-select -p`)
- The version of Carthage you're using
- The command that was used to update the frameworks e.g. `carthage update --platform iOS`

Thanks in advance!

**Comment by rwbutler** [comment]
@muiscatron @inPhilly Hoping this is fixed now? Am going to close this issue for now as I haven't heard any further but happy to re-open if it turns out there's still a problem.
