### ISSUE TITLE
Importing using SPM: Reachability missing

### ISSUE THREAD

**Issue by crspybits** [rwbutler/Connectivity#57]
I've added the git repo to my project, and when I do:

`import Connectivity`

I get:

<img width="956" alt="Screen Shot 2021-03-29 at 12 25 32 AM" src="https://user-images.githubusercontent.com/5758762/112795171-5b025000-9025-11eb-80c7-d56c0ceb555f.png">

Looking at the Package.swift and the source code, it looks like Reachability ought to be included.

Thanks!

**Comment by rwbutler** [comment]
Hi @crspybits thanks for reporting this issue - quick question do you experience this if you added Connectivity via SPM to a brand new app project as well? Thanks in advance.

**Comment by larryonoff** [comment]
I have the same issue. Down library has solution, see https://github.com/johnxnguyen/Down/pull/266.

**Comment by rwbutler** [comment]
Thanks for reporting @larryonoff, @dwsolberg it would be great if you could some information on the issue itself. Are you trying to import Connectivity into a Package.swift without a Xcode project? Trying to work the circumstances necessary to recreate the issue.

**Comment by larryonoff** [comment]
@rwbutler Our team has SDK for all our apps. One of the dependency has `Connectivity`. So we're in the process of migrating to SPM and faced with the issue.

The solution that I has at the moment is on the screenshot below
<img width="658" alt="Screenshot 2021-07-29 at 14 46 38" src="https://user-images.githubusercontent.com/372616/127486585-c4d7d31c-19cf-4a4c-a9b6-7c62afb099d6.png">

I checked how Facebook manages dependencies https://github.com/facebook/facebook-ios-sdk/blob/master/Package.swift.

**Comment by larryonoff** [comment]
Please check https://github.com/rwbutler/Connectivity/pull/62

**Comment by rwbutler** [comment]
@larryonoff Thanks for the PR - have merged 👍

**Comment by larryonoff** [comment]
> @larryonoff Thanks for the PR - have merged 👍

please release! 🥇

**Comment by rwbutler** [comment]
@larryonoff Done! 👍

**Comment by larryonoff** [comment]
@rwbutler awesome! thanks! 👍 

@crspybits could you please confirm that your issue was fixed.

**Comment by rwbutler** [comment]
Closing this one for now - if it turns out that this is still an issue let me know and I'll re-open.

**Comment by crspybits** [comment]
Thanks. I'm using `Hyperconnectivity` currently. I've made note. I may try `Connectivity` again later.
