### ISSUE TITLE
README/Documentation Appears Out of Date

### ISSUE THREAD

**Issue by bradley** [rwbutler/Connectivity#58]
It appears that `connectedViaWWAN` and `connectedViaWWANWithoutInternet` are actually named `connectedViaCellular` and `connectedViaCellularWithoutInternet`. I was unable to get such switch statements over connection status working without making this change within my code.

**Comment by rwbutler** [comment]
@Bradley Thanks for flagging this - will update!

**Comment by rwbutler** [comment]
@bradley Updated in 5.1.0 👍
