### ISSUE TITLE
Adding checks for Ethernet connection

### ISSUE THREAD

**Issue by jackaustin328** [rwbutler/Connectivity#59]
**Is your feature request related to a problem? Please describe.**
Currently the repo supports having connections through WiFi and through Cellular, but you can also connect iOS devices to Ethernet by using a USB cable to connect the iOS Device to a macOS device, and enabling Internet Sharing. It would be helpful to add this connection type to the repository. 

**Describe the solution you'd like**
Being able to monitor Ethernet connections along with the other connection types.

**Comment by rwbutler** [comment]
Hi @jackaustin328 this is part of release 5.1.0 - hope this helps!
