### ISSUE TITLE
tvOS Support?

### ISSUE THREAD

**Issue by MosheAtOwal** [rwbutler/Connectivity#6]
Hey,

Thanks for the awesome looking library! (It's well documented, too.)

When I run `carthage update "Connectivity" --no-use-binaries --platform tvOS`, I get the following error:

> *** Skipped building Connectivity due to the error:
> Dependency "Connectivity" has no shared framework schemes for any of the platforms: tvOS

I followed the Readme and built for iOS, and then tried to add the iOS framework to my tvOS app _just in case_ this was one of those fancy single-binary-multi-platform frameworks. It failed, as expected, with this error:

> Module file was created for incompatible target x86_64-apple-ios8.0-simulator: /Users/...redacted.../Carthage/Build/iOS/Connectivity.framework/Modules/Connectivity.swiftmodule/x86_64.swiftmodule

Thinking about it, I can understand why a tvOS device has a different set of reachability requirements, but the underlying ability to detect network connections is useful. In a cross-platform module that needs to check for internet access, having cross platform support would be useful.

Is this lack of support intentional? Are you open to a PR adding support for tvOS?

**Comment by rwbutler** [comment]
Hey there and thanks! There's no intentional reason for not supporting tvOS - support for it wasn't ever added only because it wasn't something I needed when it was in development. I've added support for it in 2.0.4 - this seems to build using Carthage. Hope this helps!

**Comment by MosheAtOwal** [comment]
Thank you!
