### ISSUE TITLE
App open and Airplane Mode on from Control Center

### ISSUE THREAD

**Issue by vishaldroisys** [rwbutler/Connectivity#60]
Hello,

i hope you are doing well.

As i have implemented "COnnectivity" framework for my app and we have functionality that when we reachable to internet then uploading images to AWS S3.

But we failed in case of cellular device and doing airplane mode on/off or data mode enable/disable.

Thanks in advance.

**Comment by rwbutler** [comment]
Hi @vishaldroisys thanks for letting me know about this - could you provide me with a little more information around the issue you're experiencing please?

When you say "failed" around Airplane mode on / off do you mean that Connectivity didn't report a change in Internet connectivity on toggling Airplane mode? If so, please could you let me know how you determined this? What device did you use connected to what networks etc. Thanks in advance.

**Comment by vishaldroisys** [comment]
Hi @rwbutler Yes are right while toggling airplane mode on off it has not providing state

**Comment by rwbutler** [comment]
@vishaldroisys Are you testing this on a device? If you could provide the information requested it would be appreciated thanks.

**Comment by vishaldroisys** [comment]
@rwbutler yes i have tested on iPad devices.

And secondary thing is that it is also not providing reachability when mobile data enable/disable.

Information: App open -> Open Control Center and enable airplane mode -> Closing Control Center

**Comment by rwbutler** [comment]
@vishaldroisys I've tested this today in the sample app using version 5.2.0 which seems to be behaving as expected. I'm closing the ticket for now but if you experience further issues with this let me know and I'll reopen.
