### ISSUE TITLE
Building Connectivity with Carthage fails

### ISSUE THREAD

**Issue by ttuygun** [rwbutler/Connectivity#65]
**Describe the bug**
Building Connectivity with Carthage fails

**To Reproduce**
1. Create an empty project with following `Cartfile` requirement:
`github "rwbutler/connectivity" == 5.3.0`
2. Build and run in device

**Expected behavior**
Build without error

**Actual behavior**
Fails with error

**Screenshots**
<img width="1268" alt="CleanShot 2022-07-17 at 23 52 58@2x" src="https://user-images.githubusercontent.com/10091984/179424349-3a7aa2b4-74ed-4e6d-90f7-817b57065529.png">

**Environment**
Xcode 13.4.1
Swift version 5.6.1
Carthage 0.38.0

**Comment by ttuygun** [comment]
https://github.com/rwbutler/Connectivity/pull/66

**Comment by rwbutler** [comment]
@ttuygun Thanks for the PR 👍 Have merged.
