### ISSUE TITLE
Allow URLRequest & URL

### ISSUE THREAD

**Issue by BrunoMiguens** [rwbutler/Connectivity#67]
**Is your feature request related to a problem? Please describe.**
Currently, we have no way to perform health checks besides using a standard `GET` request or fetching a file. This is fine for most cases. In my case, we're using GraphQL, forcing us to use a `POST` to perform a health check query. If we try to fetch it using a `GET`, we'll report errors on the server side which we're trying to avoid.

Also, there's no easy way to add headers which may be required if the endpoint or file has some validation or protection.

The issue is also opened on the Hyperconnectivity repo - https://github.com/rwbutler/Hyperconnectivity/issues/10 - it seems the repo is not actively maintained.

**Describe the solution you'd like**
As commented in the Hyperconnectivity repo (with an MR opened), we could use either an `URL` or `URLRequest`. This way, we don't need to make any drastic changes and still open the door to many more useful features and customisation when pinging or polling some servers to check internet connectivity.

**Describe alternatives you've considered**
We could create different functions or use an enum with some extensions to simplify the implementation. The last option will introduce breaking changes when updating; however, they are very isolated.

**Additional context**
N/A

**Comment by rwbutler** [comment]
@BrunoMiguens This should be resolved in 6.1.0.
