### ISSUE TITLE
Update podspec on cocoapods 

### ISSUE THREAD

**Issue by orenidan** [rwbutler/Connectivity#69]
**Describe**
Hi, it would be great if someone can update the podspec to the latest version on cocoapods 
https://github.com/CocoaPods/Specs/blob/master/Specs/9/b/d/Connectivity/5.0.0/Connectivity.podspec.json
Thanks!

**Comment by rwbutler** [comment]
Hi @orenidan - thanks for letting me know about this. Unfortunately there's an issue with Cocoapods itself currently which prevents pushing new podspecs:

https://github.com/CocoaPods/CocoaPods/issues/11547

I'm not aware of a workaround just yet.

**Comment by rwbutler** [comment]
Update: @orenidan I've worked around the issue and you should find the latest version published on Cocoapods now.

**Comment by orenidan** [comment]
Thank you 🙏
