### ISSUE TITLE
Failed connectivity URL

### ISSUE THREAD

**Issue by konstantin-tcherkashin** [rwbutler/Connectivity#75]
https://captive.apple.com/hotspot-detect.html (1 of 2 defaultConnectivityURLs) is now having invalid certificate, so that isConnected is always false.

**Comment by konstantin-tcherkashin** [comment]
Probably a replacement for something more reliable is needed

**Comment by rwbutler** [comment]
Thanks for flagging this - it looks as though Apple have issued a new certificate now.
![Screenshot 2023-04-03 at 09 42 25](https://user-images.githubusercontent.com/1029504/229457909-f416cdfa-9ffb-4b35-a14a-9108e973685c.png)
