### ISSUE TITLE
Changes in 6.1.0 are breaking but no major version release

### ISSUE THREAD

**Issue by Zandor300** [rwbutler/Connectivity#78]
The changes made in 6.1.0 are breaking changes. I have Connectivity as a dependency of another library and I have pinned it to 6.x.x. Now when I try to install the latest version of my library, I get compile errors since I am using `connectivityURLs` which has been removed.

This property should have had automatic translation between the old property and the new property until a 7.0 version is released which is when the `connectivityURLs` could be removed.  That would follow correct [Semantic Versioning](https://semver.org/).

Please fix this issue and restore `connectivityURLs` in a 6.1.1 version.

@rwbutler

**Comment by rwbutler** [comment]
Thanks @Zandor300 for letting me know about this - will have a fix shortly.
