### ISSUE TITLE
'checkConnectivity' is inaccessible due to 'fileprivate' protection level

### ISSUE THREAD

**Issue by BurierAbdalwahhabElia** [rwbutler/Connectivity#8]
I copy same your viewController and same your storyborad and get this above error !!!

**Comment by rwbutler** [comment]
Could you post the code that doesn’t work for me to take a look at? It will help me find where the problem lies - thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BurierAbdalwahhabElia** [comment]
I think I fixed the problem but I want to check connectiviy in app delegate please, how to doing that, I try but the problems such as "is inaccessible due to 'fileprivate' protection level" appear for me.
thanks advanced bro

**Comment by BurierAbdalwahhabElia** [comment]
hi, I fix everything and your library very amazing

**Comment by rwbutler** [comment]
Glad everything is working for you 👍🏻
