### ISSUE TITLE
Privacy manifest

### ISSUE THREAD

**Issue by Panajev** [rwbutler/Connectivity#82]
**Is your feature request related to a problem? Please describe.**
Hello @rwbutler does this project plan / need to add a privacy manifest to simplify compliance with Apple’s guidelines post May 1st?

**Comment by rwbutler** [comment]
@Panajev Thanks for flagging I'll review today.

**Comment by rwbutler** [comment]
@Panajev Apologies for the delay - have created a new release with a privacy manifest:

https://github.com/rwbutler/Connectivity/releases/tag/7.0.0

**Comment by Panajev** [comment]
Nice, thank you!Sent from my iPhoneOn 14 May 2024, at 16:26, Ross Butler ***@***.***> wrote:﻿
@Panajev Apologies for the delay - have created a new release with a privacy manifest:
https://github.com/rwbutler/Connectivity/releases/tag/7.0.0
