### ISSUE TITLE
Connectivity 7.0.0 isn't published to Cocoapods.

### ISSUE THREAD

**Issue by Zandor300** [rwbutler/Connectivity#83]
Version 7.0.0 isn't released on Cocoapods.

See https://cocoapods.org/pods/Connectivity where it shows Connectivity 6.1.1 at the top:

<img width="1220" alt="Screenshot 2024-06-10 at 23 19 10" src="https://github.com/rwbutler/Connectivity/assets/6069593/a435dec6-0fe0-435d-9b57-ce845542699e">

**Comment by rwbutler** [comment]
Thanks for flagging @Zandor300

**Comment by rwbutler** [comment]
@Zandor300  8.0.0 is now published to Cocoapods
