### ISSUE TITLE
https://github.com/rwbutler/Connectivity#known-issues

### ISSUE THREAD

**Issue by Q-000** [rwbutler/Connectivity#85]
**Have read the known issues? **
[ ] Yes, I have read and am familiar with the list of [known issues](https://github.com/rwbutler/Connectivity#known-issues).

**Have tested on a physical device? **
[ ] Yes, I have tested on physical iOS device and the reported issue is still present.

**Does code retain the `Connectivity` object? **
[ ] Yes, my implementation has a strong reference to the `Connectivity` object so that it is not deallocated during use.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rwbutler** [comment]
This appears to be the template with no information added therefore closing.
